/**
 * Replay Engine (ADR-0010): golden frames from literal envelopes (Spec v3
 * conformance seeds), determinism/purity, gap honesty, fidelity rules,
 * digest rendering, and the M8 perf budgets.
 */
import { readFileSync, rmSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";
import type { ChronicleEvent, SessionId } from "@gigaichronicle/schema";
import { newId } from "@gigaichronicle/schema";
import {
  EventEngine,
  EventLog,
  fixedGitReader,
  frameAt,
  generateSessionDigests,
  renderSessionDigest,
  replaySession,
  sessionEvents,
} from "../src/index.js";
import { WORKSPACE, makeTempChronicleDir, promptEvent } from "./helpers/events.js";

const SES = "ses_01ARZ3NDEKTSV4RRFFQ69G5FA0" as SessionId;
const WKS = "wks_01ARZ3NDEKTSV4RRFFQ69G5FA1";

/** Literal, fully deterministic envelopes — the golden-frame fixture. */
function fixtureEvents(): ChronicleEvent[] {
  const base = (index: number, type: string, payload: unknown, extra: object = {}) =>
    ({
      v: 1,
      id: `evt_01ARZ3NDEKTSV4RRFFQ69G5F${"ABCDEFGHJK"[index]}${"0123456789"[index]}`,
      ts: `2026-07-10T09:0${index}:00.000Z`,
      type,
      session: SES,
      actor: { kind: "human" },
      git: { head: "9fc1b2a", branch: "feat/auth", dirty: [] },
      payload,
      meta: {
        provider: "example-tool@1.0.0",
        workspace: WKS,
        schema: `${type}/1`,
        visibility: "shared",
      },
      ...extra,
    }) as unknown as ChronicleEvent;

  return [
    base(0, "SessionStarted", { title: "Auth rework", resumedFrom: null }),
    base(1, "PromptSubmitted", { text: "Add refresh-token rotation" }),
    base(2, "AIResponseReceived", { text: "Plan: rotate + revoke family.", inResponseTo: null }, { actor: { kind: "agent" } }),
    base(3, "ToolExecuted", { tool: "edit", outcome: "success", summary: "src/auth/refresh.ts", durationMs: 900 }, { actor: { kind: "agent" } }),
    base(4, "FileModified", { paths: ["src/auth/refresh.ts", "src/auth/session.ts"] }, { actor: { kind: "agent" } }),
    base(5, "FilesAccepted", { paths: ["src/auth/refresh.ts"], responseEvent: null }),
    base(6, "GitCommitCreated", { sha: "9fc1b2a", subject: "auth: rotate refresh tokens", branch: "feat/auth" }),
    base(7, "CaptureGap", { reason: "torn-write", detail: "one line lost" }, { actor: { kind: "system" } }),
    base(8, "SessionEnded", { reason: "completed" }, { actor: { kind: "system" } }),
  ];
}

describe("replaySession (golden frames)", () => {
  it("reduces the fixture exactly — Spec v3 conformance seed", () => {
    const frames = replaySession(fixtureEvents());
    expect(frames).toHaveLength(9);
    expect(frames[8]).toMatchSnapshot();

    const last = frames[8];
    expect(last?.conversation.map((t) => t.role)).toEqual(["human", "agent"]);
    expect(last?.workingSet).toEqual([
      { path: "src/auth/refresh.ts", status: "accepted", lastEventId: fixtureEvents()[5]?.id },
      { path: "src/auth/session.ts", status: "modified", lastEventId: fixtureEvents()[4]?.id },
    ]);
    expect(last?.git.commits).toHaveLength(1);
    expect(last?.endedReason).toBe("completed");
  });

  it("gap honesty: gaps surface and flip fidelity full → partial at the gap frame", () => {
    const frames = replaySession(fixtureEvents());
    expect(frames[6]?.fidelity).toBe("full"); //   before the gap
    expect(frames[7]?.fidelity).toBe("partial"); // the gap surfaces
    expect(frames[7]?.gaps).toHaveLength(1);
    expect(frames[8]?.fidelity).toBe("partial"); // and never un-happens
  });

  it("lossy providers cap fidelity at lossy (manual capture is honest)", () => {
    const events = fixtureEvents().map((e) => ({
      ...e,
      meta: { ...e.meta, provider: "manual@0" },
    })) as ChronicleEvent[];
    expect(replaySession(events)[8]?.fidelity).toBe("lossy");
  });

  it("determinism + purity: identical output on repeat, input untouched", () => {
    const events = fixtureEvents();
    const snapshot = JSON.stringify(events);
    const a = replaySession(events);
    const b = replaySession(events);
    expect(b).toEqual(a);
    expect(JSON.stringify(events)).toBe(snapshot); // never mutated
  });

  it("frameAt is exact-by-construction", () => {
    const events = fixtureEvents();
    const all = replaySession(events);
    expect(frameAt(events, 4)).toEqual(all[4]);
    expect(frameAt(events, -1)).toBeNull();
    expect(frameAt(events, 99)).toBeNull();
  });
});

describe("digest rendering", () => {
  it("final frame → stable markdown with the generated marker", () => {
    const digest = renderSessionDigest(SES, replaySession(fixtureEvents()));
    expect(digest.startsWith("<!-- generated by chronicle;")).toBe(true);
    expect(digest).toContain("# Auth rework");
    expect(digest).toContain("⚠ Capture gaps");
    expect(digest).toContain("✅ accepted: `src/auth/refresh.ts`");
    expect(digest).toMatchSnapshot();
  });
});

describe("replay from the real store", () => {
  const dirs: string[] = [];
  afterEach(() => {
    for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true });
  });

  it("engine-emitted session replays and digests idempotently", async () => {
    const dir = makeTempChronicleDir("replay-e2e-");
    dirs.push(dir);
    const engine = await EventEngine.open(dir, {
      workspaceId: WORKSPACE,
      provider: { id: "example-tool", version: "1.0.0" },
      gitReader: fixedGitReader({ head: "9fc1b2a", branch: "main", dirty: [] }),
      fsyncIntervalMs: 0,
    });
    const session = newId("session");
    await engine.emit({ type: "SessionStarted", session, actor: { kind: "human" }, payload: { title: "t", resumedFrom: null } });
    await engine.emit({ type: "PromptSubmitted", session, actor: { kind: "human" }, payload: { text: "hello" } });
    await engine.emit({ type: "SessionEnded", session, actor: { kind: "system" }, payload: { reason: "completed" } });
    await engine.close();

    const log = await EventLog.open(dir, { workspaceId: WORKSPACE, fsyncIntervalMs: 0 });
    const frames = replaySession(await sessionEvents(log, session));
    expect(frames).toHaveLength(3);
    expect(frames[2]?.conversation).toHaveLength(1);

    const first = await generateSessionDigests(dir, log);
    expect(first.written).toHaveLength(1);
    const digestFile = path.join(dir, first.written[0] as string);
    const content = readFileSync(digestFile, "utf8");
    const second = await generateSessionDigests(dir, log);
    expect(second.written).toEqual([]); // idempotent
    expect(readFileSync(digestFile, "utf8")).toBe(content);
    await log.close();
  });
});

describe("replay budgets (perf/budgets.json)", () => {
  const budgets = JSON.parse(
    readFileSync(
      path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../../perf/budgets.json"),
      "utf8",
    ),
  ) as { budgets: Array<{ id: string; budgetMs: number | null }> };
  const budget = (id: string): number => budgets.budgets.find((b) => b.id === id)?.budgetMs as number;

  it("1k-event session full replay + frame step within budget (best of 3)", () => {
    const session = newId("session");
    const events: ChronicleEvent[] = [];
    for (let i = 0; i < 1000; i++) events.push(promptEvent(session, `prompt number ${i}`));

    let bestFull = Number.POSITIVE_INFINITY;
    let bestStep = Number.POSITIVE_INFINITY;
    for (let batch = 0; batch < 3; batch++) {
      const t0 = performance.now();
      const frames = replaySession(events);
      bestFull = Math.min(bestFull, performance.now() - t0);
      expect(frames).toHaveLength(1000);

      const t1 = performance.now();
      const frame = frames[500];
      const again = replaySession(events.slice(0, 501))[500];
      bestStep = Math.min(bestStep, performance.now() - t1);
      expect(again?.conversation.length).toBe(frame?.conversation.length);
    }
    // eslint-disable-next-line no-console
    console.log(`replay 1k: full ${bestFull.toFixed(1)}ms · step ${bestStep.toFixed(2)}ms`);
    expect(bestFull).toBeLessThan(budget("replay.session-1k.full"));
    expect(bestStep).toBeLessThan(budget("replay.session-1k.full")); // step = bounded re-fold
  });
});
