/**
 * Generated-file marker — ARCHITECTURE.md §7.2 rule 2. Generated files
 * declare themselves on their first line and are idempotently regenerated;
 * curated files are the user's and are never rewritten.
 */

export const GENERATED_MARKER = "<!-- generated by chronicle; edits will be overwritten -->";

/** Prefix `content` with the marker line. */
export function withGeneratedMarker(content: string): string {
  return `${GENERATED_MARKER}\n${content}`;
}

/** True when `content` declares itself generated (marker on first line). */
export function isGeneratedContent(content: string): boolean {
  const firstLine = content.slice(0, content.indexOf("\n") === -1 ? undefined : content.indexOf("\n"));
  return firstLine.trim() === GENERATED_MARKER;
}
